#!/bin/bash

# ConnectBest Chat Application Architecture Overview
# This script provides a comprehensive overview of the application architecture

set -e

echo "🏗️  ConnectBest Chat Application Architecture"
echo "=============================================="
echo ""

# Color codes for better visualization
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 OVERVIEW${NC}"
echo "============"
echo "• Full-stack real-time chat application"
echo "• Microservices architecture on AWS ECS Fargate"
echo "• Multi-container deployment with ALB routing"
echo "• Serverless WebSocket API for real-time messaging"
echo "• MongoDB Atlas for data persistence"
echo ""

echo -e "${GREEN}🏗️  ARCHITECTURE LAYERS${NC}"
echo "======================"
echo ""

echo -e "${CYAN}┌─ FRONTEND LAYER ─────────────────────────────────┐${NC}"
echo "│ Technology: Next.js 15 (App Router)             │"
echo "│ Runtime: Node.js 18                             │"
echo "│ Container: Frontend Container (Port 3000)       │"
echo "│ Features:                                        │"
echo "│  • Server-side rendering (SSR)                  │"
echo "│  • Static file serving                          │"
echo "│  • NextAuth.js authentication                   │"
echo "│  • Tailwind CSS styling                         │"
echo "│  • TypeScript                                   │"
echo -e "${CYAN}└──────────────────────────────────────────────────┘${NC}"
echo ""

echo -e "${YELLOW}┌─ API LAYER ──────────────────────────────────────┐${NC}"
echo "│ Technology: Flask (Python 3.12)                 │"
echo "│ Runtime: Gunicorn + Eventlet                    │"
echo "│ Container: Backend Container (Port 5001)        │"
echo "│ Features:                                        │"
echo "│  • REST API endpoints                           │"
echo "│  • JWT authentication                           │"
echo "│  • File upload handling                         │"
echo "│  • Socket.IO integration                        │"
echo "│  • MongoDB ODM                                  │"
echo -e "${YELLOW}└──────────────────────────────────────────────────┘${NC}"
echo ""

echo -e "${PURPLE}┌─ REAL-TIME LAYER ────────────────────────────────┐${NC}"
echo "│ Technology: AWS API Gateway WebSocket + Lambda  │"
echo "│ Runtime: Node.js 20 (Serverless)               │"
echo "│ Storage: DynamoDB (Connection tracking)         │"
echo "│ Features:                                        │"
echo "│  • Real-time message delivery                   │"
echo "│  • Connection management                        │"
echo "│  • Channel-based routing                        │"
echo "│  • Auto-scaling                                 │"
echo -e "${PURPLE}└──────────────────────────────────────────────────┘${NC}"
echo ""

echo -e "${RED}┌─ DATA LAYER ─────────────────────────────────────┐${NC}"
echo "│ Database: MongoDB Atlas (Cloud)                 │"
echo "│ Collections:                                     │"
echo "│  • users (authentication, profiles)             │"
echo "│  • channels (chat rooms, permissions)           │"
echo "│  • messages (content, threads, reactions)       │"
echo "│  • message_files (file attachments)             │"
echo "│  • user_channel_read (read receipts)            │"
echo "│  • threads (reply tracking)                     │"
echo -e "${RED}└──────────────────────────────────────────────────┘${NC}"
echo ""

echo -e "${BLUE}🔀 REQUEST FLOW${NC}"
echo "==============="
echo ""
echo "┌─ User Browser ─────────────────────────────────────────────────────────┐"
echo "│                                                                        │"
echo "│  Frontend (Next.js)          API Calls              Backend (Flask)   │"
echo "│  ┌─────────────┐              ┌──────────────┐       ┌──────────────┐  │"
echo "│  │   Port 3000 │◄─────────────┤ ALB Routing  │──────►│   Port 5001  │  │"
echo "│  │             │   /          │              │  /api │              │  │"
echo "│  │ • Pages     │              │ Path-Based   │       │ • REST API   │  │"
echo "│  │ • Components│              │ Routing      │       │ • Auth       │  │"
echo "│  │ • Static    │              │              │       │ • Database   │  │"
echo "│  └─────────────┘              └──────────────┘       └──────────────┘  │"
echo "│                                      │                       │         │"
echo "└──────────────────────────────────────┼───────────────────────┼─────────┘"
echo "                                       │                       │"
echo "                                       ▼                       ▼"
echo "                            ┌─────────────────┐     ┌────────────────┐"
echo "                            │ AWS WebSocket   │     │ MongoDB Atlas  │"
echo "                            │ API Gateway     │     │                │"
echo "                            │ + Lambda        │     │ • Documents    │"
echo "                            │ + DynamoDB      │     │ • Indexes      │"
echo "                            └─────────────────┘     │ • Replication  │"
echo "                                                    └────────────────┘"
echo ""

echo -e "${GREEN}🏗️  AWS INFRASTRUCTURE${NC}"
echo "======================"
echo ""
echo "ECS Fargate Cluster: chat-app-cluster"
echo "├── Task Definition: chat-app (Multi-container)"
echo "│   ├── Frontend Container (chat-frontend:latest)"
echo "│   │   ├── Image: ECR Private/Public"
echo "│   │   ├── CPU: 256, Memory: 512MB"
echo "│   │   ├── Port: 3000"
echo "│   │   └── Health Check: /"
echo "│   └── Backend Container (chat-backend:latest)"
echo "│       ├── Image: ECR Private/Public"
echo "│       ├── CPU: 768, Memory: 1536MB"
echo "│       ├── Port: 5001"
echo "│       └── Health Check: /api/health"
echo "├── ECS Service: chat-app-service"
echo "│   ├── Desired Count: 1 (Auto-scaling: 1-3)"
echo "│   ├── Launch Type: Fargate"
echo "│   ├── Network: awsvpc mode"
echo "│   └── Security Groups: ALB + ECS"
echo "└── Application Load Balancer: chat-app-alb"
echo "    ├── Listeners: HTTP (Port 80)"
echo "    ├── Target Groups:"
echo "    │   ├── Frontend TG (Port 3000) - Default /*"
echo "    │   └── Backend TG (Port 5001) - /api/*"
echo "    └── Health Checks: HTTP-based"
echo ""

echo -e "${YELLOW}🔄 CI/CD PIPELINE${NC}"
echo "=================="
echo ""
echo "GitHub Actions Workflow: 'Build & Deploy Multi-Container to ECS'"
echo "├── Trigger: Push to main branch"
echo "├── Build Phase:"
echo "│   ├── Build Frontend Docker image (Dockerfile.frontend)"
echo "│   ├── Build Backend Docker image (Dockerfile.backend)"
echo "│   ├── Push to ECR Public + Private repositories"
echo "│   └── Tag: latest, git-sha, branch-name"
echo "├── Deploy Phase:"
echo "│   ├── Install CDK dependencies (npm install)"
echo "│   ├── Compile TypeScript (npm run build)"
echo "│   ├── Deploy infrastructure (cdk deploy)"
echo "│   └── Update ECS service with new images"
echo "└── Verification:"
echo "    ├── Wait for service stability"
echo "    ├── Health check validation"
echo "    └── Output deployment URL"
echo ""

echo -e "${PURPLE}📊 MONITORING & OBSERVABILITY${NC}"
echo "=============================="
echo ""
echo "CloudWatch Integration:"
echo "├── Log Groups:"
echo "│   ├── /ecs/chat-app (ECS Container logs)"
echo "│   │   ├── chat-frontend/* (Next.js logs)"
echo "│   │   └── chat-backend/* (Flask logs)"
echo "│   └── /aws/lambda/websocket-* (WebSocket logs)"
echo "├── Metrics:"
echo "│   ├── ECS: CPU, Memory, Task count"
echo "│   ├── ALB: Request count, Latency, Errors"
echo "│   └── Lambda: Invocations, Duration, Errors"
echo "└── Alarms: (Can be configured)"
echo "    ├── High CPU/Memory usage"
echo "    ├── ALB 5xx errors"
echo "    └── WebSocket connection failures"
echo ""

echo -e "${CYAN}🌐 NETWORKING${NC}"
echo "=============="
echo ""
echo "VPC Configuration:"
echo "├── VPC: chat-app-vpc"
echo "├── Subnets:"
echo "│   ├── Public Subnets (2 AZs) - ALB"
echo "│   └── Private Subnets (2 AZs) - ECS Tasks"
echo "├── Internet Gateway: Public access"
echo "├── NAT Gateways: Outbound for private subnets"
echo "└── Security Groups:"
echo "    ├── ALB SG: HTTP (80), HTTPS (443) from 0.0.0.0/0"
echo "    └── ECS SG: Port 3000, 5001 from ALB SG only"
echo ""

echo -e "${GREEN}💰 COST ESTIMATION${NC}"
echo "=================="
echo ""
echo "Monthly AWS Costs (Estimated):"
echo "├── ECS Fargate:"
echo "│   ├── Task (1.25 vCPU, 2GB RAM): ~\$15-25/month"
echo "│   └── Auto-scaling (1-3 tasks): ~\$15-75/month"
echo "├── Application Load Balancer: ~\$16/month"
echo "├── CloudWatch Logs (retention): ~\$2-5/month"
echo "├── WebSocket API:"
echo "│   ├── API Gateway: \$1.00/million messages"
echo "│   ├── Lambda: Free tier (1M requests/month)"
echo "│   └── DynamoDB: Free tier (25GB storage)"
echo "└── Total Estimated: \$35-100/month"
echo ""
echo "External Services:"
echo "├── MongoDB Atlas: Free tier (512MB)"
echo "├── Domain/DNS: ~\$12/year (optional)"
echo "└── SSL Certificate: Free (Let's Encrypt)"
echo ""

echo -e "${YELLOW}🔐 SECURITY${NC}"
echo "============"
echo ""
echo "Authentication & Authorization:"
echo "├── NextAuth.js (Frontend session management)"
echo "├── JWT tokens (API authentication)"
echo "├── Google OAuth integration"
echo "├── 2FA support (TOTP)"
echo "└── Role-based access control"
echo ""
echo "Network Security:"
echo "├── VPC private networking"
echo "├── Security group restrictions"
echo "├── ALB SSL termination (configurable)"
echo "└── MongoDB Atlas network whitelist"
echo ""

echo -e "${BLUE}🔗 IMPORTANT URLs${NC}"
echo "=================="
echo ""
echo "Current Deployment:"
echo "├── Application: http://chat-app-alb-2064082767.us-west-2.elb.amazonaws.com"
echo "├── Health Check: http://chat-app-alb-2064082767.us-west-2.elb.amazonaws.com/api/health"
echo "├── WebSocket: wss://v68x792yd5.execute-api.us-west-2.amazonaws.com/prod"
echo "└── MongoDB: mongodb+srv://connectbest.fyufpj1.mongodb.net"
echo ""
echo "GitHub Repository:"
echo "├── Source: https://github.com/ConnectBest/chat"
echo "├── Actions: https://github.com/ConnectBest/chat/actions"
echo "└── Releases: https://github.com/ConnectBest/chat/releases"
echo ""

echo -e "${GREEN}✅ DEPLOYMENT STATUS${NC}"
echo "===================="
echo ""
if command -v gh &> /dev/null && gh auth status &> /dev/null; then
    echo "Latest GitHub Actions Run:"
    gh run list --limit 1 --json status,name,createdAt,conclusion,url | jq -r '.[] | "├── Status: \(.status // "unknown") | \(.conclusion // "running") | \(.name) | \(.createdAt) | \(.url)"' 2>/dev/null || echo "├── Unable to fetch GitHub Actions status"
else
    echo "├── GitHub CLI not available or not authenticated"
fi
echo ""

echo -e "${CYAN}📚 DOCUMENTATION${NC}"
echo "=================="
echo ""
echo "Key Documentation Files:"
echo "├── README.md - Project overview"
echo "├── CLAUDE.md - Architecture guide for Claude Code"
echo "├── DEPLOYMENT_GUIDE.md - Manual deployment steps"
echo "├── backend/README.md - Backend API documentation"
echo "├── websocket-api/README.md - WebSocket deployment guide"
echo "└── infrastructure/ - AWS CDK infrastructure as code"
echo ""

echo -e "${YELLOW}🛠️  DEVELOPMENT WORKFLOW${NC}"
echo "========================="
echo ""
echo "Local Development:"
echo "├── Frontend: npm run dev (Port 3000)"
echo "├── Backend: cd backend && python app.py (Port 5001)"
echo "├── Database: MongoDB Atlas (Cloud)"
echo "└── WebSocket: Deploy separately with SAM CLI"
echo ""
echo "Production Deployment:"
echo "├── Push to main branch"
echo "├── GitHub Actions triggers automatically"
echo "├── Multi-container images built and pushed"
echo "├── CDK deploys infrastructure updates"
echo "└── ECS service updates with zero-downtime"
echo ""

echo -e "${GREEN}🎉 ARCHITECTURE OVERVIEW COMPLETE${NC}"
echo "=================================="
echo ""
echo "This multi-container microservices architecture provides:"
echo "✅ Scalability: Auto-scaling ECS tasks based on demand"
echo "✅ Reliability: Multi-AZ deployment with health checks"
echo "✅ Performance: CDN-ready static assets, efficient caching"
echo "✅ Security: VPC networking, IAM roles, encrypted data"
echo "✅ Maintainability: Infrastructure as Code, CI/CD automation"
echo "✅ Cost-Effective: Pay-per-use serverless components"
echo ""
echo "🔗 Current Application: http://chat-app-alb-2064082767.us-west-2.elb.amazonaws.com"
echo ""